version: "3.7"
services:
  server:
    build:
      context: ./server
    stdin_open: true
    tty: true
    volumes:
      - ./server/:/workspace/server
      - bundle:/bundle
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
volumes:
  bundle:
    driver: local
